name: Publish docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Version Name
        id: extract_version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            if (context.payload.ref.startsWith('refs/tags/')) {
              return context.payload.ref.replace(/refs\/tags\/v/, '');
            }
            return 'dev';
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create version file
        run: 'echo -e "parameters:\n  app.current_version: $VERSION" > config/packages/version.yaml'
        env:
          VERSION: ${{ steps.extract_version.outputs.result }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/rikudousage/lemmy-schedule
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=dev
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
